import type { MatechTypography } from '../theme.types';

export const matechDefaultTypography: MatechTypography = {
  fontFamily: '"Lato", "Segoe UI", sans-serif',
  button: {
    fontFamily: '"Lato", "Segoe UI", sans-serif',
    fontWeight: 900,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  variants: {
    h1: {
      fontFamily: '"Lato", "Segoe UI", sans-serif',
      fontSize: '2.25rem',
      fontWeight: 800,
      letterSpacing: '-0.02em',
      lineHeight: 1.15,
      textTransform: 'none',
    },
    h2: {
      fontFamily: '"Lato", "Segoe UI", sans-serif',
      fontSize: '1.875rem',
      fontWeight: 800,
      letterSpacing: '-0.02em',
      lineHeight: 1.2,
      textTransform: 'none',
    },
    h3: {
      fontFamily: '"Lato", "Segoe UI", sans-serif',
      fontSize: '1.5rem',
      fontWeight: 800,
      letterSpacing: '-0.015em',
      lineHeight: 1.25,
      textTransform: 'none',
    },
    h4: {
      fontFamily: '"Lato", "Segoe UI", sans-serif',
      fontSize: '1.25rem',
      fontWeight: 700,
      letterSpacing: '-0.01em',
      lineHeight: 1.3,
      textTransform: 'none',
    },
    h5: {
      fontFamily: '"Lato", "Segoe UI", sans-serif',
      fontSize: '1.125rem',
      fontWeight: 700,
      letterSpacing: '-0.01em',
      lineHeight: 1.35,
      textTransform: 'none',
    },
    h6: {
      fontFamily: '"Lato", "Segoe UI", sans-serif',
      fontSize: '1rem',
      fontWeight: 700,
      letterSpacing: '-0.01em',
      lineHeight: 1.4,
      textTransform: 'none',
    },
    subtitle1: {
      fontFamily: '"Lato", "Segoe UI", sans-serif',
      fontSize: '1rem',
      fontWeight: 600,
      letterSpacing: '0',
      lineHeight: 1.5,
      textTransform: 'none',
    },
    subtitle2: {
      fontFamily: '"Lato", "Segoe UI", sans-serif',
      fontSize: '0.875rem',
      fontWeight: 600,
      letterSpacing: '0',
      lineHeight: 1.45,
      textTransform: 'none',
    },
    body1: {
      fontFamily: '"Lato", "Segoe UI", sans-serif',
      fontSize: '1rem',
      fontWeight: 400,
      letterSpacing: '0',
      lineHeight: 1.6,
      textTransform: 'none',
    },
    body2: {
      fontFamily: '"Lato", "Segoe UI", sans-serif',
      fontSize: '0.875rem',
      fontWeight: 400,
      letterSpacing: '0',
      lineHeight: 1.55,
      textTransform: 'none',
    },
    caption: {
      fontFamily: '"Lato", "Segoe UI", sans-serif',
      fontSize: '0.75rem',
      fontWeight: 400,
      letterSpacing: '0',
      lineHeight: 1.45,
      textTransform: 'none',
    },
    overline: {
      fontFamily: '"Lato", "Segoe UI", sans-serif',
      fontSize: '0.75rem',
      fontWeight: 700,
      letterSpacing: '0.08em',
      lineHeight: 1.4,
      textTransform: 'uppercase',
    },
    lead: {
      fontFamily: '"Lato", "Segoe UI", sans-serif',
      fontSize: '1.125rem',
      fontWeight: 400,
      letterSpacing: '0',
      lineHeight: 1.65,
      textTransform: 'none',
    },
  },
};
